#ifndef _BSP_H
#define _BSP_H

#include "bsp_sys.h"
#include "bsp_key.h"
#include "bsp_dac.h"
#include "bsp_param.h"
#include "bsp_ir.h"
#include "bsp_audio.h"
#include "bsp_music.h"
#include "bsp_led.h"
#include "bsp_fs.h"
#include "bsp_bt.h"
#include "bsp_eq.h"
#include "bsp_charge.h"
#include "bsp_piano.h"
#include "bsp_id3_tag.h"
#include "bsp_record.h"
#include "bsp_aux.h"
#include "bsp_i2c.h"
#include "bsp_karaok.h"
#include "bsp_lrc.h"
#include "bsp_ble.h"
#include "bsp_tkey.h"
#include "bsp_anc.h"
#include "bsp_vusb_uart.h"
#include "bsp_smart_vhouse.h"
#include "bsp_iodm.h"
#include "bsp_tws_sync.h"
#include "bsp_uart.h"
#include "bsp_fot.h"
#include "bsp_tbox_qtest.h"
#include "bsp_iis_ext.h"
#include "bsp_hearaid.h"

#endif
